db.inventory.insertMany([
  {
    inventory_number: "PC001",
    purchase_year: 2022,
    warranty_period: 3,
    processor: "Intel Core i5",
    licensed_until: 2021,
    memory: "8 GB",
    disk_capacity: "256 GB",
    licensed_software: ["Windows 10", "Microsoft Office 365"],
  },
  {
    inventory_number: "PC002",
    purchase_year: 2022,
    warranty_period: 2,
    processor: "Intel Core i3",
    licensed_until: 2020,
    memory: "16 GB",
    disk_capacity: "512 GB",
    licensed_software: ["Windows 10", "Adobe Creative Cloud"],
  },
  {
    inventory_number: "PC003",
    purchase_year: 2023,
    warranty_period: 3,
    processor: "Intel Core i7",
    licensed_until: 2021,
    memory: "32 GB",
    disk_capacity: "1 TB",
    licensed_software: ["Windows 11", "Autodesk AutoCAD"],
  },
  {
    inventory_number: "PC004",
    purchase_year: 2019,
    warranty_period: 2,
    processor: "Intel Core i3",
    licensed_until: 2021,
    memory: "4 GB",
    disk_capacity: "128 GB",
    licensed_software: ["Windows 11", "Autodesk AutoCAD"],
  },
  {
    inventory_number: "PC005",
    purchase_year: 2022,
    warranty_period: 3,
    processor: "Intel Core i7",
    licensed_until: 2021,
    memory: "16 GB",
    disk_capacity: "512 GB",
    licensed_software: ["Windows 10", "Adobe Photoshop"],
  },
  {
    inventory_number: "PC006",
    purchase_year: 2025,
    warranty_period: 2,
    processor: "Intel Core i7",
    licensed_until: 2021,
    memory: "16 GB",
    disk_capacity: "1 TB",
    licensed_software: ["Windows 10", "Microsoft Office 365"],
  }
])